module('swlcalc');

test('should initate swlcalc submodules', 8, function() {
    swlcalc.init();
    ok(swlcalc);
    ok(swlcalc.data);
    ok(swlcalc.button);
    ok(swlcalc.select);
    ok(swlcalc.buttonBar);
    ok(swlcalc.summary);
    ok(swlcalc.export);
    ok(swlcalc.import);
});

//TODO/TEST : to add assertions for primary stats when implemented
//TODO/TEST : to add assertions for signet text when implemented
test('should import from hash', 170, function() {
    location.hash = 'weapon=3,4,3,19,3,2,2,13,0,4,0&weapon2=3,7,2,29,4,3,1,15,0,8,0&head=3,1,2,24,4,3,2,18,1,1,16&finger=2,1,1,20,5,4,3,15,4,1,2&neck=1,1,3,6,3,2,1,20,1,1,3&wrist=5,1,2,68,3,3,2,6,5,1,8&luck=1,1,1,10,2,2,1,18,3,1,13&waist=5,1,1,2,4,5,3,8,3,1,16&occult=1,1,3,19,5,1,3,2,2,1,10'
    swlcalc.init();

    // Summary
    equal($('#stat-item-power').html(), '538');
    equal($('#stat-power-rating').html(), '4388');
    equal($('#stat-weapon-power').html(), '1577');
    // equal($('#stat-attack-rating').html(), '474');
    // equal($('#stat-heal-rating').html(), '1091');
    // equal($('#stat-hitpoints').html(), '10458');
    // equal($('#stat-combat-power').html(), '278');
    // equal($('#stat-heal-power').html(), '1091');
    equal($('#stat-critical-rating').html(), '+1598');
    equal($('#stat-critical-chance').html(), '18.6 %');
    equal($('#stat-critical-power').html(), '+1858');
    equal($('#stat-critical-power-percentage').html(), '120.6 %');
    equal($('#stat-hit-rating').html(), '+1539');
    equal($('#stat-glance-reduction').html(), '30.3 %');
    equal($('#stat-defense-rating').html(), '+1313');
    equal($('#stat-glance-chance').html(), '12.9 %');
    equal($('#stat-evade-rating').html(), '+1805');
    equal($('#stat-evade-chance').html(), '12.4 %');
    // equal($('#stat-physical-protection').html(), '+660');
    // equal($('#stat-magical-protection').html(), '+300');

    ok($('#weapon-slot').is(':visible'));
    equal($('#weapon-total-item-power').html(), '400');
    equal($('#weapon-name').html(), ': Blood');
    equal($('#weapon-wtype').val(), 'blood');
    equal($('#weapon-rarity').val(), 'epic');
    equal($('#weapon-quality').val(), 'mkIII');
    equal($('#weapon-level').val(), '19');
    equal($('#weapon-power-value').html(), '+1577');
    equal($('#weapon-item-power').html(), '264');
    equal($('#weapon-glyph').val(), 'critical-rating');
    equal($('#weapon-glyph-rarity').val(), 'epic');
    equal($('#weapon-glyph-quality').val(), 'simple');
    equal($('#weapon-glyph-level').val(), '13');
    equal($('#weapon-glyph-value').html(), '+329');
    equal($('#weapon-glyph-item-power').html(), '136');
    equal($('#weapon-signet').val(), '4');
    equal($('#weapon-signet-rarity').val(), undefined);
    equal($('#weapon-signet-level').val(), undefined);
    equal($('#weapon-signet-item-power').html(), undefined);

    ok(!$('#weapon2-slot').is(':visible'));
    equal($('#weapon2-total-item-power').html(), '581');
    equal($('#weapon2-name').html(), ': Shotgun');
    equal($('#weapon2-wtype').val(), 'shotgun');
    equal($('#weapon2-rarity').val(), 'epic');
    equal($('#weapon2-quality').val(), 'mkII');
    equal($('#weapon2-level').val(), '29');
    equal($('#weapon2-power-value').html(), '+1809');
    equal($('#weapon2-item-power').html(), '315');
    equal($('#weapon2-glyph').val(), 'critical-power');
    equal($('#weapon2-glyph-rarity').val(), 'mythic');
    equal($('#weapon2-glyph-quality').val(), 'crude');
    equal($('#weapon2-glyph-level').val(), '15');
    equal($('#weapon2-glyph-value').html(), '+491');
    equal($('#weapon2-glyph-item-power').html(), '266');
    equal($('#weapon2-signet').val(), '8');
    equal($('#weapon2-signet-rarity').val(), undefined);
    equal($('#weapon2-signet-level').val(), undefined);
    equal($('#weapon2-signet-item-power').html(), undefined);

    equal($('#head-total-item-power').html(), '487');
    equal($('#head-itemId').val(), '1');
    equal($('#head-rarity').val(), 'epic');
    equal($('#head-quality').val(), 'luminous');
    equal($('#head-level').val(), '24');
    equal($('#head-power-value').html(), '+1113');
    equal($('#head-item-power').html(), '252');
    equal($('#head-glyph').val(), 'critical-power');
    equal($('#head-glyph-rarity').val(), 'mythic');
    equal($('#head-glyph-quality').val(), 'simple');
    equal($('#head-glyph-level').val(), '18');
    equal($('#head-glyph-value').html(), '+580');
    equal($('#head-glyph-item-power').html(), '226');
    equal($('#head-signet').val(), '1');
    equal($('#head-signet-rarity').val(), 'standard');
    equal($('#head-signet-level').val(), '16');
    equal($('#head-signet-item-power').html(), '10');

    equal($('#finger-total-item-power').html(), '571');
    equal($('#finger-itemId').val(), '1');
    equal($('#finger-rarity').val(), 'superior');
    equal($('#finger-quality').val(), 'faded');
    equal($('#finger-level').val(), '20');
    equal($('#finger-power-value').html(), '+314');
    equal($('#finger-item-power').html(), '113');
    equal($('#finger-glyph').val(), 'evade-rating');
    equal($('#finger-glyph-rarity').val(), 'legendary');
    equal($('#finger-glyph-quality').val(), 'intricate');
    equal($('#finger-glyph-level').val(), '15');
    equal($('#finger-glyph-value').html(), '+1052');
    equal($('#finger-glyph-item-power').html(), '369');
    equal($('#finger-signet').val(), '1');
    equal($('#finger-signet-rarity').val(), 'mythic');
    equal($('#finger-signet-level').val(), '2');
    equal($('#finger-signet-item-power').html(), '89');

    equal($('#neck-total-item-power').html(), '143');
    equal($('#neck-itemId').val(), '1');
    equal($('#neck-rarity').val(), 'standard');
    equal($('#neck-quality').val(), 'radiant');
    equal($('#neck-level').val(), '6');
    equal($('#neck-power-value').html(), '+70');
    equal($('#neck-item-power').html(), '13');
    equal($('#neck-glyph').val(), 'critical-rating');
    equal($('#neck-glyph-rarity').val(), 'epic');
    equal($('#neck-glyph-quality').val(), 'crude');
    equal($('#neck-glyph-level').val(), '20');
    equal($('#neck-glyph-value').html(), '+339');
    equal($('#neck-glyph-item-power').html(), '128');
    equal($('#neck-signet').val(), '1');
    equal($('#neck-signet-rarity').val(), 'standard');
    equal($('#neck-signet-level').val(), '3');
    equal($('#neck-signet-item-power').html(), '2');

    equal($('#wrist-total-item-power').html(), '1292');
    equal($('#wrist-itemId').val(), '1');
    equal($('#wrist-rarity').val(), 'legendary');
    equal($('#wrist-quality').val(), 'luminous');
    equal($('#wrist-level').val(), '68');
    equal($('#wrist-power-value').html(), '+1951');
    equal($('#wrist-item-power').html(), '1026');
    equal($('#wrist-glyph').val(), 'critical-power');
    equal($('#wrist-glyph-rarity').val(), 'epic');
    equal($('#wrist-glyph-quality').val(), 'simple');
    equal($('#wrist-glyph-level').val(), '6');
    equal($('#wrist-glyph-value').html(), '+270');
    equal($('#wrist-glyph-item-power').html(), '94');
    equal($('#wrist-signet').val(), '1');
    equal($('#wrist-signet-rarity').val(), 'legendary');
    equal($('#wrist-signet-level').val(), '8');
    equal($('#wrist-signet-item-power').html(), '172');

    equal($('#luck-total-item-power').html(), '136');
    equal($('#luck-itemId').val(), '1');
    equal($('#luck-rarity').val(), 'standard');
    equal($('#luck-quality').val(), 'faded');
    equal($('#luck-level').val(), '10');
    equal($('#luck-power-value').html(), '+53');
    equal($('#luck-item-power').html(), '22');
    equal($('#luck-glyph').val(), 'critical-rating');
    equal($('#luck-glyph-rarity').val(), 'superior');
    equal($('#luck-glyph-quality').val(), 'crude');
    equal($('#luck-glyph-level').val(), '18');
    equal($('#luck-glyph-value').html(), '+174');
    equal($('#luck-glyph-item-power').html(), '58');
    equal($('#luck-signet').val(), '1');
    equal($('#luck-signet-rarity').val(), 'epic');
    equal($('#luck-signet-level').val(), '13');
    equal($('#luck-signet-item-power').html(), '55');

    equal($('#waist-total-item-power').html(), '846');
    equal($('#waist-itemId').val(), '1');
    equal($('#waist-rarity').val(), 'legendary');
    equal($('#waist-quality').val(), 'faded');
    equal($('#waist-level').val(), '2');
    equal($('#waist-power-value').html(), '+775');
    equal($('#waist-item-power').html(), '591');
    equal($('#waist-glyph').val(), 'defense-rating');
    equal($('#waist-glyph-rarity').val(), 'mythic');
    equal($('#waist-glyph-quality').val(), 'intricate');
    equal($('#waist-glyph-level').val(), '8');
    equal($('#waist-glyph-value').html(), '+560');
    equal($('#waist-glyph-item-power').html(), '196');
    equal($('#waist-signet').val(), '1');
    equal($('#waist-signet-rarity').val(), 'epic');
    equal($('#waist-signet-level').val(), '16');
    equal($('#waist-signet-item-power').html(), '59');

    equal($('#occult-total-item-power').html(), '386');
    equal($('#occult-itemId').val(), '1');
    equal($('#occult-rarity').val(), 'standard');
    equal($('#occult-quality').val(), 'radiant');
    equal($('#occult-level').val(), '19');
    equal($('#occult-power-value').html(), '+112');
    equal($('#occult-item-power').html(), '42');
    equal($('#occult-glyph').val(), 'hit-rating');
    equal($('#occult-glyph-rarity').val(), 'legendary');
    equal($('#occult-glyph-quality').val(), 'intricate');
    equal($('#occult-glyph-level').val(), '2');
    equal($('#occult-glyph-value').html(), '+783');
    equal($('#occult-glyph-item-power').html(), '322');
    equal($('#occult-signet').val(), '1');
    equal($('#occult-signet-rarity').val(), 'superior');
    equal($('#occult-signet-level').val(), '10');
    equal($('#occult-signet-item-power').html(), '22');
});
